[package]
name = "blwf"
version = "0.3.0"
edition = "2024"
license = "MIT OR Apache-2.0"
keywords = ["wgpu", "winit", "graphics"]
description = "A framework for building cross-platform applications with wgpu and winit"
repository = "https://github.com/blindley/blwf"
readme = "README.md"

[dependencies]
anyhow = "1.0"
winit = { version = "0.30", features = ["android-native-activity"] }
wgpu = "29.0"
pollster = "0.3"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1"
console_log = "1.0"
wgpu = { version = "29.0", features = ["webgl"]}
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = [
    "Document",
    "Window",
    "Element",
]}
